### ISSUE TITLE
USER STORY: Admin 1

### ISSUE THREAD

**Issue by Johneriksson88** [Johneriksson88/My-first-agile-project#4]
In order to **manage the poll system** as an **administrator**, i can **login as and admin**.

#Acceptance Criteria:

- Login page can be reached in navigation bar
- The admin can create an account by using email address and password
- The password must be minimun 8 chars long and include at least one capital letter and at least one number

# Tasks

- [] Create login page
- [] Add create account form
- [] Add login page to navigation
- [] Encrypt password
