### ISSUE TITLE
USER STORY: Admin 2

### ISSUE THREAD

**Issue by Johneriksson88** [Johneriksson88/My-first-agile-project#5]
In order to **add new polls** as an **administrator**, i can **add a poll by providing a question and a chosen number of answer options**.

#Acceptance Criteria:

- A link to create poll form can be found in admin menu
- Create poll form should have a Question field and answer fields
- Admin can add more answer fields by clicking a plus icon

# Tasks

- [] Create "Add poll" form and link it in admin menu
- [] Add JavaScript to create more answers, standard number should be 3
- [] Add placeholder text
