### ISSUE TITLE
USER STORY: Admin 3

### ISSUE THREAD

**Issue by Johneriksson88** [Johneriksson88/My-first-agile-project#6]
In order to **view older polls** as an **administrator**, i can **easily find the old polls and view collected data from the answers**.

#Acceptance Criteria:

- View older polls can be found in admin menu
- Poll data should be presented in colored bars with percentages next to them

# Tasks

- [] Create view older polls page
- [] Create backend code to present the data, preferably using Pandas 
- [] Present older polls in a table under Older polls page
